const fetch = require('node-fetch');

// Villa data with image fields as strings


const villasData = [
  {
    id: 1,
    name: "Villa Kaia",
    location: "Saligao Goa, India",
    guests: 8,
    bedrooms: 4,
    beds: 4,
    price: 15300,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.8,
    image: "anandvilla1",
    description:
      "Located in the peaceful village of Saligao, Villa Kaia an elegant 4-bedroom retreat offers a perfect Goan escape with comfort and style.",
    fullDescription:
      "Located in the peaceful village of Saligao, Villa Kaia an elegant 4-bedroom retreat offers a perfect Goan escape with comfort and style. This stunning property features modern amenities, spacious rooms, and beautiful outdoor spaces perfect for relaxation and entertainment.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 2,
    name: "Villa Scapes",
    location: "Siolim Goa, India",
    guests: 7,
    bedrooms: 3,
    beds: 3,
    price: 9900,
    type: "VILLA",
    amenities: ["Private Pool"],
    rating: 4.6,
    image: "anandvilla2",
    description: "A beautiful villa in Siolim offering stunning views and modern amenities for a perfect getaway.",
    fullDescription:
      "A beautiful villa in Siolim offering stunning views and modern amenities for a perfect getaway. This property combines traditional Goan architecture with contemporary comfort.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 3,
    name: "Villa Dahlia",
    location: "Arpora Goa, India",
    guests: 10,
    bedrooms: 4,
    beds: 5,
    price: 24999,
    type: "VILLA",
    amenities: ["Private Pool", "Shared Pool"],
    rating: 4.9,
    image: "anandvilla3",
    description: "Luxurious villa in Arpora with premium amenities and spacious accommodation for large groups.",
    fullDescription:
      "Luxurious villa in Arpora with premium amenities and spacious accommodation for large groups. Features include multiple pools, elegant interiors, and beautiful outdoor spaces.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 4,
    name: "Villa Serenity",
    location: "Candolim Goa, India",
    guests: 6,
    bedrooms: 3,
    beds: 3,
    price: 12500,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.7,
    image: "anandvilla4",
    description: "Peaceful retreat in Candolim offering tranquility and modern comfort.",
    fullDescription:
      "Peaceful retreat in Candolim offering tranquility and modern comfort. Perfect for families and groups seeking a serene vacation experience.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 5,
    name: "Ocean View Apartment",
    location: "Baga Goa, India",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    price: 8500,
    type: "APARTMENT",
    amenities: ["Shared Pool"],
    rating: 4.4,
    image: "anandvilla5",
    description: "Modern apartment with ocean views in the heart of Baga.",
    fullDescription:
      "Modern apartment with ocean views in the heart of Baga. Close to beaches, restaurants, and nightlife.",
    facilities: [
      { name: "Shared Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 6,
    name: "Villa Paradise",
    location: "Anjuna Goa, India",
    guests: 12,
    bedrooms: 5,
    beds: 6,
    price: 32000,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.8,
    image: "anandvilla6",
    description: "Expansive villa in Anjuna perfect for large groups and celebrations.",
    fullDescription:
      "Expansive villa in Anjuna perfect for large groups and celebrations. Features multiple bedrooms, entertainment areas, and beautiful gardens.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 7,
    name: "Coastal Retreat",
    location: "Morjim Goa, India",
    guests: 8,
    bedrooms: 4,
    beds: 4,
    price: 18500,
    type: "VILLA",
    amenities: ["Private Pool"],
    rating: 4.6,
    image: "anandvilla7",
    description: "Beachfront villa in Morjim with stunning coastal views.",
    fullDescription: "Beachfront villa in Morjim with stunning coastal views and direct beach access.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 8,
    name: "Sunset Apartment",
    location: "Calangute Goa, India",
    guests: 5,
    bedrooms: 2,
    beds: 3,
    price: 7200,
    type: "APARTMENT",
    amenities: ["Shared Pool", "Pet Friendly"],
    rating: 4.3,
    image: "anandvilla8",
    description: "Cozy apartment with sunset views in Calangute.",
    fullDescription: "Cozy apartment with sunset views in Calangute, perfect for couples and small families.",
    facilities: [
      { name: "Shared Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 9,
    name: "Casa Sol",
    location: "Assagao Goa, India",
    guests: 9,
    bedrooms: 4,
    beds: 5,
    price: 17800,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.7,
    image: "anandvilla9",
    description: "Traditional Goan villa with lush gardens and a private pool.",
    fullDescription:
      "Traditional Goan villa in Assagao with lush gardens, private pool, and classic interiors. Ideal for families.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 10,
    name: "Lagoon Residence",
    location: "Nerul Goa, India",
    guests: 6,
    bedrooms: 3,
    beds: 3,
    price: 14250,
    type: "VILLA",
    amenities: ["Private Pool", "Shared Pool"],
    rating: 4.5,
    image: "anandvilla10",
    description: "Modern villa on the lagoon with tranquil poolside views.",
    fullDescription: "Modern villa on the Nerul lagoon with tranquil poolside views, a blend of luxury and nature.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Shared Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
    ],
    images: ["anandvilla2.jpeg", "anandvilla4.jpeg"],
  },
  {
    id: 11,
    name: "Palm Grove Apartment",
    location: "Vagator Goa, India",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    price: 8700,
    type: "APARTMENT",
    amenities: ["Shared Pool"],
    rating: 4.2,
    image: anandvilla11,
    description: "Apartment surrounded by palm trees, close to Vagator beach.",
    fullDescription:
      "Apartment surrounded by palm trees, close to Vagator beach, with a shared pool and modern facilities.",
    facilities: [
      { name: "Shared Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 12,
    name: "Blue Haven Villa",
    location: "Mapusa Goa, India",
    guests: 14,
    bedrooms: 6,
    beds: 8,
    price: 35500,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.9,
    image: "anandvilla12",
    description: "Large villa with private pool and garden, ideal for big groups.",
    fullDescription:
      "Large villa with private pool and a spacious garden in Mapusa, ideal for family gatherings and celebrations.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
      { name: "Barbecue", image: "/microwave.png" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 13,
    name: "Hilltop Mansion",
    location: "Porvorim Goa, India",
    guests: 15,
    bedrooms: 7,
    beds: 9,
    price: 42000,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.8,
    image: "anandvilla13",
    description: "Luxury mansion on a hilltop with panoramic views and infinity pool.",
    fullDescription:
      "Luxury mansion on a hilltop with panoramic views, infinity pool, and premium amenities for a lavish stay.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Microwave", image: "Kitchen" },
      { name: "Gym", image: "/microwave.png" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 14,
    name: "Sunshine Studio",
    location: "Colva Goa, India",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    price: 5400,
    type: "STUDIO",
    amenities: ["Shared Pool"],
    rating: 4.0,
    image: "anandvilla14",
    description: "Bright and airy studio apartment near Colva beach.",
    fullDescription: "Bright and airy studio apartment near Colva beach, perfect for couples or solo travelers.",
    facilities: [
      { name: "Shared Pool", image: "Pool" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 15,
    name: "Gardenia Villa",
    location: "Panjim Goa, India",
    guests: 8,
    bedrooms: 4,
    beds: 4,
    price: 16200,
    type: "VILLA",
    amenities: ["Private Pool", "Pet Friendly"],
    rating: 4.5,
    image: "anandvilla15",
    description: "Elegant villa in Panjim with lush garden and private pool.",
    fullDescription:
      "Elegant villa in Panjim with lush garden, private pool, and all modern comforts for a relaxing holiday.",
    facilities: [
      { name: "Private Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
      { name: "Kitchen", image: "Kitchen" },
      { name: "Barbecue", image: "/microwave.png" },
    ],
    images: "empireAnandVillaImages",
  },
  {
    id: 16,
    name: "Coral Bay Apartment",
    location: "Morjim Goa, India",
    guests: 3,
    bedrooms: 1,
    beds: 2,
    price: 6900,
    type: "APARTMENT",
    amenities: ["Shared Pool"],
    rating: 4.1,
    image: "anandvilla16",
    description: "Cozy apartment with pool access close to Morjim beach.",
    fullDescription: "Cozy apartment with pool access and walking distance to Morjim beach, ideal for small families.",
    facilities: [
      { name: "Shared Pool", image: "Pool" },
      { name: "Free Parking", image: "Parking" },
      { name: "AC", image: "Ac" },
      { name: "WiFi", image: "Wifi" },
    ],
    images: "empireAnandVillaImages",
  },
]

async function seedVillas() {
  // Ensure the backend server is running before executing this script
  console.log('Seeding villas to the database...');
  try {
    const res = await fetch('http://localhost:5000/api/villas/add', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(villasData)
    });

    if (!res.ok) {
      throw new Error(`HTTP error! status: ${res.status}`);
    }

    const data = await res.json();
    console.log('✅ Seed result:', data);
  } catch (err) {
    console.error('❌ Seeding error:', err.message);
    console.log('Please make sure your backend server is running on http://localhost:5000');
  }
}

seedVillas();